# Generated by Django 4.2 on 2024-11-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
