# Generated by Django 4.2 on 2024-11-11 20:17

from django.db import migrations

def set_default_location_for_existing_posts(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Location = apps.get_model('locations', 'Location')
    
    # Fetch the default location
    default_location = Location.objects.get(name="Unknown")
    
    # Update existing posts without a location to use the default
    Post.objects.filter(location__isnull=True).update(location=default_location)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_location'),
        ('locations', '0002_create_default_location'),
    ]

    operations = [
        migrations.RunPython(set_default_location_for_existing_posts),
    ]
