# Generated by Django 4.2 on 2024-11-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_set_default_location_for_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locality',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
