# Generated by Django 3.2.25 on 2024-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dtxscaulc/image/upload/v1725906099/default_profile_yvwtw0.jpg', upload_to='images/'),
        ),
    ]
