# Generated by Django 4.2 on 2024-11-09 09:40

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    categories = [
        'nature', 'sports', 'music', 'cooking', 'other'
    ]
    for category_name in categories:
        Category.objects.get_or_create(name=category_name)

class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),  
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]