# Generated by Django 4.2 on 2024-11-15 17:20

from django.db import migrations
from django_countries import countries

def populate_full_country_list(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    for index, (code, name) in enumerate(countries, start=1):
        Location.objects.get_or_create(id=index, country=code, name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_create_default_location'),
    ]

    operations = [
        migrations.RunPython(populate_full_country_list),
    ]
