# Generated by Django 4.2 on 2024-11-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_populate_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='locality',
        ),
    ]
