# Generated by Django 4.2 on 2024-11-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_rename_name_location_locality'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('locality', 'country')},
        ),
    ]
