# Generated by Django 4.2 on 2024-11-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='location',
            name='locality',
        ),
    ]
